import { useState, useEffect, createContext, useContext } from "react";

const SURL = "https://gjzbzugjatdqjdafhqsx.supabase.co";
const SKEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqemJ6dWdqYXRkcWpkYWZocXN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY4NDgwMTYsImV4cCI6MjA5MjQyNDAxNn0.PmqN2EH9mE1cv9Z0x8oVYZjXipFKAv-mbp2mPGcJjzY";

let TOKEN = SKEY;

const H = () => ({
  "Content-Type": "application/json",
    apikey: SKEY,
      Authorization: `Bearer ${TOKEN}`,
      });

      const db = (table) => {
        const url = (q = "") => `${SURL}/rest/v1/${table}${q}`;

          const handle = async (r) => {
              const text = await r.text();
                  console.log("DB:", table, r.status, text);

                      if (!r.ok) throw new Error(text);
                          return text ? JSON.parse(text) : null;
                            };

                              return {
                                  getAll: (select = "*") =>
                                        fetch(url(`?select=${select}`), { headers: H() }).then(handle),

                                            insert: (body) =>
                                                  fetch(url(""), {
                                                          method: "POST",
                                                                  headers: { ...H(), Prefer: "return=representation" },
                                                                          body: JSON.stringify(body),
                                                                                }).then(handle),

                                                                                    update: (col, val, body) =>
                                                                                          fetch(url(`?${col}=eq.${val}`), {
                                                                                                  method: "PATCH",
                                                                                                          headers: { ...H(), Prefer: "return=representation" },
                                                                                                                  body: JSON.stringify(body),
                                                                                                                        }).then(handle),

                                                                                                                            remove: (col, val) =>
                                                                                                                                  fetch(url(`?${col}=eq.${val}`), {
                                                                                                                                          method: "DELETE",
                                                                                                                                                  headers: H(),
                                                                                                                                                        }).then(handle),
                                                                                                                                                          };
                                                                                                                                                          };

                                                                                                                                                          const TC = createContext(null);
                                                                                                                                                          const useToast = () => useContext(TC);

                                                                                                                                                          function Toasts({ children }) {
                                                                                                                                                            const [list, set] = useState([]);

                                                                                                                                                              const add = (msg, type = "ok") => {
                                                                                                                                                                  const id = Date.now();
                                                                                                                                                                      set((t) => [...t, { id, msg, type }]);
                                                                                                                                                                          setTimeout(() => set((t) => t.filter((x) => x.id !== id)), 3000);
                                                                                                                                                                            };

                                                                                                                                                                              return (
                                                                                                                                                                                  <TC.Provider value={add}>
                                                                                                                                                                                        {children}
                                                                                                                                                                                              <div style={{ position: "fixed", bottom: 20, right: 10 }}>
                                                                                                                                                                                                      {list.map((t) => (
                                                                                                                                                                                                                <div key={t.id} style={{ color: "#fff", marginBottom: 6 }}>
                                                                                                                                                                                                                            {t.msg}
                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                        </TC.Provider>
                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                          /* ---------------- COURSES ---------------- */

                                                                                                                                                                                                                                                          function Courses() {
                                                                                                                                                                                                                                                            const toast = useToast();
                                                                                                                                                                                                                                                              const [courses, setCourses] = useState([]);
                                                                                                                                                                                                                                                                const [fees, setFees] = useState([]);
                                                                                                                                                                                                                                                                  const [name, setName] = useState("");
                                                                                                                                                                                                                                                                    const [amount, setAmount] = useState("");

                                                                                                                                                                                                                                                                      const load = async () => {
                                                                                                                                                                                                                                                                          try {
                                                                                                                                                                                                                                                                                const c = await db("Course").getAll();
                                                                                                                                                                                                                                                                                      const f = await db("Fees").getAll();
                                                                                                                                                                                                                                                                                            setCourses(c || []);
                                                                                                                                                                                                                                                                                                  setFees(f || []);
                                                                                                                                                                                                                                                                                                      } catch (e) {
                                                                                                                                                                                                                                                                                                            console.error(e);
                                                                                                                                                                                                                                                                                                                  toast("Load failed", "err");
                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                          useEffect(() => { load(); }, []);

                                                                                                                                                                                                                                                                                                                            const add = async () => {
                                                                                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                                                                                      if (!name) return toast("Enter name", "err");

                                                                                                                                                                                                                                                                                                                                            const res = await db("Course").insert({ Name: name });
                                                                                                                                                                                                                                                                                                                                                  const id = res?.[0]?.id;

                                                                                                                                                                                                                                                                                                                                                        if (id && amount) {
                                                                                                                                                                                                                                                                                                                                                                await db("Fees").insert({
                                                                                                                                                                                                                                                                                                                                                                          course_id: id,
                                                                                                                                                                                                                                                                                                                                                                                    Amount: parseInt(amount),
                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                        toast("Added!");
                                                                                                                                                                                                                                                                                                                                                                                                              setName("");
                                                                                                                                                                                                                                                                                                                                                                                                                    setAmount("");
                                                                                                                                                                                                                                                                                                                                                                                                                          load();
                                                                                                                                                                                                                                                                                                                                                                                                                              } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                    console.error(e);
                                                                                                                                                                                                                                                                                                                                                                                                                                          toast("Insert failed", "err");
                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h2>Courses</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <input placeholder="Name" value={name} onChange={(e) => setName(e.target.value)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input placeholder="Fee" value={amount} onChange={(e) => setAmount(e.target.value)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button onClick={add}>Add</button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {courses.map((c) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const fee = fees.find((f) => f.course_id === c.id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div key={c.id}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {c.Name} - ₹{fee?.Amount || 0}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        /* ---------------- STUDENTS ---------------- */

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        function Students() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const toast = useToast();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const [students, setStudents] = useState([]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const [name, setName] = useState("");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const load = async () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const s = await db("Student").getAll();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                setStudents(s || []);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          toast("Load failed", "err");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  useEffect(() => { load(); }, []);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const add = async () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              await db("Student").insert({ Name: name });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    toast("Added!");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          setName("");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                load();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          toast("Insert failed", "err");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h2>Students</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <input value={name} onChange={(e) => setName(e.target.value)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button onClick={add}>Add</button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {students.map((s) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div key={s.id}>{s.Name}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  /* ---------------- PAYMENTS ---------------- */

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  function Payments() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const toast = useToast();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const [payments, setPayments] = useState([]);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const load = async () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const p = await db("Payment").getAll();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        setPayments(p || []);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  toast("Load failed", "err");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          useEffect(() => { load(); }, []);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const add = async () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      await db("Payment").insert({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Amount: 100,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Student_id: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  toast("Added!");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        load();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  toast("Insert failed", "err");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h2>Payments</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button onClick={add}>Add Sample</button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {payments.map((p) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div key={p.id}>₹{p.Amount}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    /* ---------------- APP ---------------- */

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    export default function App() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const [page, setPage] = useState("courses");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Toasts>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ padding: 20 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button onClick={() => setPage("courses")}>Courses</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button onClick={() => setPage("students")}>Students</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button onClick={() => setPage("payments")}>Payments</button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {page === "courses" && <Courses />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {page === "students" && <Students />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {page === "payments" && <Payments />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </Toasts>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }